services:
  unit_test_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: java_bd
      POSTGRES_USER: oduvanchik
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5437:5432"

volumes:
  db: